### ISSUE TITLE
MathJax rendering is broken on some browsers

### ISSUE THREAD

**Issue by Morwenn** [Morwenn/cpp-gray#1]
From what I have heard, MathJax isn't always properly displayed on some browsers for some reason. I have no idea why.

Any fix is welcome.

**Comment by nabijaczleweli** [comment]
Use SVG

**Comment by nabijaczleweli** [comment]
Use a maths font

**Comment by Morwenn** [comment]
I don't like using images for maths :/ 

Also I have no idea how to simply generate stuff in a math font from a latex-like math dialect.

**Comment by nabijaczleweli** [comment]
Do what wikipedia does

**Comment by Morwenn** [comment]
You mean not always being consistent? :D

**Comment by Morwenn** [comment]
Fixed by e103e30e9a6a932c182bc260ca58cf5c1f7733dc.

I was using the HTTP version of MathJax's CDN, which didn't work with browsers using the HTTPS Everywhere plugin for some reason. Switching to HTTPS did the trick.
