### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by nabijaczleweli** [Morwenn/cpp-gray#4]

**Comment by Morwenn** [comment]
I have a bunch of compile-time tests, but they randomly fail for no apparent reason. It looks like I have compile-time UB in them or something :/

**Comment by nabijaczleweli** [comment]
Where are they

**Comment by Morwenn** [comment]
Here: 90c3e7248bcba3d2dc0e9358eed792ac7e75ea00

**Comment by Morwenn** [comment]
Decent enough to close the issue?

**Comment by nabijaczleweli** [comment]
yeah
